I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/config.rpy", line 1, in script
    init python:
  File "game/config.rpy", line 5, in <module>
    pygame.init()
NameError: name 'pygame' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/config.rpy", line 1, in script
    init python:
  File "/Applications/renpy-6.99.14.1-sdk/renpy/ast.py", line 848, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-6.99.14.1-sdk/renpy/python.py", line 1812, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/config.rpy", line 5, in <module>
    pygame.init()
NameError: name 'pygame' is not defined

Darwin-17.4.0-x86_64-i386-64bit
Ren'Py 6.99.14.1.3218
 
Mon Mar 26 18:27:53 2018
